### ISSUE TITLE
min api level

### ISSUE THREAD

**Issue by beide** [beide/Droidgain#1]
could be lowered, it is 9 now

**Comment by bahaa-sharqawe** [comment]
Hi, When I import this project in android studio, a lot of problems appeared at c and h files in jni folder, what I can do in this situation? thanks..

**Comment by beide** [comment]
I am not sure, since I have not worked on this project for 4 years, and never used Android Studio. Back then I had trouble getting JNI to work, so the folder is slightly mislabeled. The jni folder contains the unmodified source code for mp3gain, and a specific makefile for compiling for Android. Since nothing has changed, the c and h files should not contain any problems.
Back when I first made this, the libraries included with the Android SDK to compile c code were faulty though, I believe the header files contained some typos, but that problem could be solved by commenting out the faulty lines from the libraries header files.

Good luck!
