### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by beide** [beide/Droidgain#2]
Droidgain is a bit hard to use atm, for example:
What does the textinput do?
The keyboard comes up automaticly

**Comment by alanthehat** [comment]
+1 
I too would like instructions, please

**Comment by beide** [comment]
I did not expect anyone to get here, since I haven't worked on this project for 4 years now.

The app is a front-end for the mp3gain executable. The text field is to input the gain level, and then it is a matter of picking files to have them processed. While it is running you don't get any real feedback, but after maybe a couple of minutes it will say it is finished.

For an explanation of what happens to your files, I recommend reading the man page for mp3gain.

**Comment by alanthehat** [comment]
This man page? -- http://dev.man-online.org/man1/mp3gain/ 
for this program? -- http://mp3gain.sourceforge.net/ 

The man page I cite quite specifically states there isn't a man page with the original project, but goes on to describe some interesting switches. Which switches do you use?
